# Generated by Django 2.0 on 2018-03-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owners_name', models.CharField(max_length=50)),
                ('mail_id', models.EmailField(max_length=100)),
                ('phone', models.PositiveIntegerField(unique=True)),
                ('address', models.CharField(default='none', max_length=500)),
                ('landmark', models.CharField(max_length=200)),
                ('city', models.CharField(choices=[('jalandhar', 'Jalandhar')], default='jalandhar', max_length=5)),
                ('state', models.CharField(choices=[('punjab', 'Punjab')], default='punjab', max_length=5)),
                ('expected_rent', models.PositiveIntegerField(default=0)),
                ('negotiable', models.BooleanField(default=False)),
                ('parking', models.CharField(choices=[('none', 'None'), ('bike', 'Bike'), ('car', 'Car')], default='none', max_length=10)),
                ('property_description', models.TextField()),
                ('owner_pic', models.ImageField(upload_to='owners/%Y/%m/%d/')),
            ],
        ),
    ]
