# Generated by Django 2.0 on 2018-03-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owners',
            name='city',
            field=models.CharField(choices=[('jalandhar', 'Jalandhar')], default='jalandhar', max_length=50),
        ),
        migrations.AlterField(
            model_name='owners',
            name='state',
            field=models.CharField(choices=[('punjab', 'Punjab')], default='punjab', max_length=50),
        ),
    ]
